### ISSUE TITLE
EasyEffects background request fails

### ISSUE THREAD

**Issue by Jonator3** [flathub/com.github.wwmm.easyeffects#37]
If the background permission is not set, EasyEffects will close by itself after a short time. Also it is not possible that EasyEffects sets the autostart entry. 

With Flatseal I can set the permission and EasyEffects shows the expected behavior. 

But this solution is not permanent, because it seems that the permission is reset. (As far as I have noticed.)

I use Arch btw

```
flatpak run com.github.wwmm.easyeffects
You have PipeWire 0.3.40 installed
This is newer or the same as PipeWire 0.3.31 required to run EasyEffects
Failed to establish dbus connection
(easyeffects:2): easyeffects-WARNING **: 15:14:16.479: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:2): easyeffects-WARNING **: 15:14:16.479: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 15:14:16.479: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 15:14:16.479: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:2): easyeffects-WARNING **: 15:14:16.769: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:2): easyeffects-WARNING **: 15:14:16.769: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 15:14:16.769: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 15:14:16.769: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:2): easyeffects-WARNING **: 15:14:17.138: effects_base_ui: webrtc voiceengine icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.

(easyeffects:2): easyeffects-WARNING **: 15:14:17.167: effects_base_ui: webrtc voiceengine icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.

(easyeffects:2): easyeffects-WARNING **: 15:14:17.520: portal: background request failed:Background request canceled
```

**Comment by vchernin** [comment]
The current implementation of background portal in EasyEffects is not ideal (also includes autostart). I have been trying to wrap my head around how to solve this properly. It is partially a UX problem, the way these permissions are presented to the user needs to be done carefully.

Hopefully I can clear up some things here though.

> If the background permission is not set, EasyEffects will close by itself after a short time. 

This is expected. However note xdg-desktop-portal kills EasyEffects, not EasyEffects itself.  

> Also it is not possible that EasyEffects sets the autostart entry.

It is supposed to be able to, however as mentioned above the current implementation is subpar.

> With Flatseal I can set the permission and EasyEffects shows the expected behavior.

This is exactly right, since now you've given EasyEffects permission to run in the background. You can also use `flatpak override`.


> But this solution is not permanent, because it seems that the permission is reset. (As far as I have noticed.)

That is not supposed to happen, out of curiosity could you tell me the state of the "autostart" and "shutdown on window close" settings within EasyEffects?

**Comment by vchernin** [comment]
@Jonator3 if you are able to, please test using the flathub-beta branch: https://github.com/wwmm/easyeffects/wiki/Package-Repositories#nightly-flatpak

It includes better portal support, and hopefully this issue doesn't occur anymore.

**Comment by vchernin** [comment]
I will close for now in favor of the upstream issue, but feel free to reopen or add a comment there. It's better now, but I can still improve it.
